-- EXTENSIONS
create extension if not exists "uuid-ossp";

-- 1. FAZENDAS
create table if not exists fazendas (
  codigo text primary key,
  nome text not null,
  regiao text,
  area_total numeric default 0,
  plantio_acumulado numeric default 0,
  muda_acumulada numeric default 0,
  observacoes text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. INSUMOS OXIFERTIL
create table if not exists insumos_oxifertil (
  id bigint generated by default as identity primary key,
  processo text,
  subprocesso text,
  produto text,
  fazenda text,
  area_talhao numeric,
  area_total_aplicada numeric,
  dose_recomendada numeric,
  insum_dose_aplicada numeric,
  quantidade_aplicada numeric,
  dif numeric,
  frente numeric,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. INSUMOS FAZENDAS
create table if not exists insumos_fazendas (
  id bigint generated by default as identity primary key,
  os numeric,
  cod numeric,
  fazenda text,
  area_talhao numeric,
  area_total_aplicada numeric,
  produto text,
  dose_recomendada numeric,
  quantidade_aplicada numeric,
  frente numeric,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. ESTOQUE
create table if not exists estoque (
  id bigint generated by default as identity primary key,
  frente text not null,
  produto text not null,
  quantidade numeric default 0,
  os_numero text,
  data_cadastro text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(frente, produto)
);

-- 5. PLANTIO DIARIO
create table if not exists plantio_diario (
  id bigint primary key,
  data text,
  responsavel text,
  observacoes text,
  frentes jsonb default '[]'::jsonb,
  insumos jsonb default '[]'::jsonb,
  qualidade jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 6. USERS
create table if not exists users (
  id uuid default uuid_generate_v4() primary key,
  username text unique not null,
  password text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- UPDATE USERS SCHEMA (Se a tabela já existir sem essas colunas)
ALTER TABLE users ADD COLUMN IF NOT EXISTS email text UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS role text DEFAULT 'user';
ALTER TABLE users ADD COLUMN IF NOT EXISTS permissions jsonb DEFAULT '{}'::jsonb;

-- RLS POLICIES FOR USERS (Fix 42501 Error)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'users' AND policyname = 'Users can read own data') THEN
        CREATE POLICY "Users can read own data" ON users FOR SELECT USING (auth.uid() = id);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'users' AND policyname = 'Users can update own data') THEN
        CREATE POLICY "Users can update own data" ON users FOR UPDATE USING (auth.uid() = id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'users' AND policyname = 'Users can insert own data') THEN
        CREATE POLICY "Users can insert own data" ON users FOR INSERT WITH CHECK (auth.uid() = id);
    END IF;
END $$;

-- Insert default admin
insert into users (username, password, role, permissions)
values ('admin', '123456', 'admin', '{"all": true}'::jsonb)
on conflict (username) do nothing;

-- 7. VIAGENS ADUBO
create table if not exists viagens_adubo (
  id bigint primary key,
  data text,
  frente text,
  fazenda text,
  origem text,
  destino text,
  produto text,
  quantidade_total numeric,
  unidade text,
  caminhao text,
  carreta1 text,
  carreta2 text,
  motorista text,
  documento_motorista text,
  transportadora text,
  observacoes text,
  bags jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 8. METAS
create table if not exists metas (
  id bigint generated by default as identity primary key,
  frente text not null,
  meta_diaria numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(frente)
);

-- 9. OS AGRICOLA
create table if not exists os_agricola (
  id uuid default uuid_generate_v4() primary key,
  numero text unique not null,
  status text,
  data_abertura date,
  data_inicio_prev date,
  data_final_prev date,
  responsavel_aplicacao text,
  empresa text,
  frente text,
  processo text,
  subprocesso text,
  fazenda text,
  setor text,
  area_total numeric,
  talhoes jsonb default '[]'::jsonb,
  produtos jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 10. TRANSPORTE COMPOSTO
CREATE TABLE IF NOT EXISTS transporte_composto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_os VARCHAR(20),
    data_abertura DATE,
    data_inicio_previsto DATE,
    data_fim_previsto DATE,
    responsavel_aplicacao VARCHAR(100),
    empresa VARCHAR(100),
    processo VARCHAR(50),
    frente VARCHAR(50),
    area_total DECIMAL(10,2),
    status VARCHAR(20),
    subprocesso VARCHAR(50),
    tipo_os VARCHAR(30),
    setor VARCHAR(50),
    codigo_fundo_agricola VARCHAR(50),
    distancia_media_km DECIMAL(5,1),
    grupo_atividade VARCHAR(50),
    atividade_agricola VARCHAR(100),
    sistema_aplicacao VARCHAR(30),
    produto VARCHAR(100),
    dose_recomendada DECIMAL(10,4),
    unidade VARCHAR(10),
    quantidade DECIMAL(10,3),
    categoria_produto VARCHAR(50),
    data_inicio_real DATE,
    data_fim_real DATE,
    anexo_caminho VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE transporte_composto ADD COLUMN IF NOT EXISTS fazenda VARCHAR(255);

CREATE INDEX IF NOT EXISTS idx_transporte_composto_numero_os ON transporte_composto (numero_os);
CREATE INDEX IF NOT EXISTS idx_transporte_composto_status ON transporte_composto (status);

-- 11. MAPEAMENTO CAMPOS PDF
CREATE TABLE IF NOT EXISTS mapeamento_campos_pdf (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pdf_field_pattern VARCHAR(255) NOT NULL,
    db_field VARCHAR(50) NOT NULL,
    transform VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

INSERT INTO mapeamento_campos_pdf (pdf_field_pattern, db_field, transform) VALUES
('Ordem de serviço - (\\d+)', 'numero_os', 'trim'),
('Data de Abertura:\\s*(\\d{2}/\\d{2}/\\d{4})', 'data_abertura', 'date_br'),
('Responsável:\\s*(.*)', 'responsavel_aplicacao', 'trim'),
('Empresa:\\s*(.*)', 'empresa', 'trim'),
('Frente:\\s*(.*)', 'frente', 'trim'),
('Produto:\\s*(.*)', 'produto', 'trim'),
('Quantidade:\\s*([\\d\\.,]+)', 'quantidade', 'decimal_br')
ON CONFLICT DO NOTHING;

-- 12. AUDIT LOGS
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.users(id),
    action TEXT NOT NULL,
    details JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable insert for all" ON public.audit_logs FOR INSERT WITH CHECK (true);

-- 13. SYSTEM SETTINGS
CREATE TABLE IF NOT EXISTS system_settings (
    key TEXT PRIMARY KEY,
    value JSONB,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access" ON system_settings FOR SELECT USING (true);
INSERT INTO system_settings (key, value) VALUES ('app_version', '{"version": "1.0.0", "timestamp": 0}'::jsonb) ON CONFLICT (key) DO NOTHING;

-- 14. EQUIPAMENTO OPERADOR
CREATE TABLE IF NOT EXISTS equipamento_operador (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plantio_diario_id BIGINT NOT NULL REFERENCES plantio_diario(id) ON DELETE CASCADE,
  trator TEXT,
  plantadora_colhedora TEXT,
  operador TEXT,
  matricula TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(plantio_diario_id)
);

-- 15. LIBERACAO COLHEITA
CREATE TABLE IF NOT EXISTS public.liberacao_colheita (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_liberacao TEXT NOT NULL UNIQUE,
    data DATE NOT NULL,
    frente TEXT,
    fazenda TEXT,
    fazenda_codigo TEXT,
    talhoes JSONB DEFAULT '[]'::jsonb,
    area_total NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'Pendente',
    observacoes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 16. METAS PLANTIO
CREATE TABLE IF NOT EXISTS metas_plantio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    frente VARCHAR(255) NOT NULL UNIQUE,
    meta_diaria NUMERIC(10, 2) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 17. OS TRANSPORTE DIARIO
CREATE TABLE IF NOT EXISTS os_transporte_diario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    os_id BIGINT REFERENCES transporte_composto(id) ON DELETE CASCADE,
    data_transporte DATE NOT NULL,
    quantidade NUMERIC(10,3) NOT NULL,
    frota VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
