-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Tabela de Fazendas
create table if not exists fazendas (
  codigo text primary key,
  nome text not null,
  regiao text,
  area_total numeric default 0,
  plantio_acumulado numeric default 0,
  muda_acumulada numeric default 0,
  observacoes text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Tabela de Insumos - Oxifertil
create table if not exists insumos_oxifertil (
  id bigint generated by default as identity primary key,
  processo text,
  subprocesso text,
  produto text,
  fazenda text,
  area_talhao numeric,
  area_total_aplicada numeric,
  dose_recomendada numeric,
  insum_dose_aplicada numeric,
  quantidade_aplicada numeric,
  dif numeric,
  frente numeric,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Tabela de Insumos - Fazendas (Geral)
create table if not exists insumos_fazendas (
  id bigint generated by default as identity primary key,
  os numeric,
  cod numeric,
  fazenda text,
  area_talhao numeric,
  area_total_aplicada numeric,
  produto text,
  dose_recomendada numeric,
  quantidade_aplicada numeric,
  frente numeric,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Tabela de Estoque
create table if not exists estoque (
  id bigint generated by default as identity primary key,
  frente text not null,
  produto text not null,
  quantidade numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(frente, produto)
);

-- Tabela de Plantio Diário
-- Armazenando estruturas complexas (frentes, insumos, qualidade) como JSONB para facilitar
create table if not exists plantio_diario (
  id bigint primary key, -- Usando o timestamp do JS como ID
  data text,
  responsavel text,
  observacoes text,
  frentes jsonb default '[]'::jsonb,
  insumos jsonb default '[]'::jsonb,
  qualidade jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Tabela de Usuários (para manter a auth simples existente)
create table if not exists users (
  id uuid default uuid_generate_v4() primary key,
  username text unique not null,
  password text not null, -- Em produção, usar hash!
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Inserir usuário admin padrão se não existir
insert into users (username, password)
values ('admin', '123456')
on conflict (username) do nothing;

create table if not exists viagens_adubo (
  id bigint primary key,
  data text,
  frente text,
  fazenda text,
  origem text,
  destino text,
  produto text,
  quantidade_total numeric,
  unidade text,
  caminhao text,
  carreta1 text,
  carreta2 text,
  motorista text,
  documento_motorista text,
  transportadora text,
  observacoes text,
  bags jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
