-- Tabela para Transporte de Composto
CREATE TABLE IF NOT EXISTS transporte_composto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_os VARCHAR(20),
    data_abertura DATE,
    data_inicio_previsto DATE,
    data_fim_previsto DATE,
    responsavel_aplicacao VARCHAR(100),
    empresa VARCHAR(100),
    processo VARCHAR(50),
    frente VARCHAR(50),
    area_total DECIMAL(10,2),
    status VARCHAR(20),
    subprocesso VARCHAR(50),
    tipo_os VARCHAR(30),
    setor VARCHAR(50),
    codigo_fundo_agricola VARCHAR(50),
    distancia_media_km DECIMAL(5,1),
    grupo_atividade VARCHAR(50),
    atividade_agricola VARCHAR(100),
    sistema_aplicacao VARCHAR(30),
    produto VARCHAR(100),
    dose_recomendada DECIMAL(10,4),
    unidade VARCHAR(10),
    quantidade DECIMAL(10,3),
    categoria_produto VARCHAR(50),
    data_inicio_real DATE,
    data_fim_real DATE,
    anexo_caminho VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_transporte_composto_numero_os ON transporte_composto (numero_os);
CREATE INDEX IF NOT EXISTS idx_transporte_composto_status ON transporte_composto (status);

-- Tabela de Mapeamento de Campos PDF (Configurável)
CREATE TABLE IF NOT EXISTS mapeamento_campos_pdf (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pdf_field_pattern VARCHAR(255) NOT NULL, -- Regex pattern
    db_field VARCHAR(50) NOT NULL, -- Campo na tabela transporte_composto
    transform VARCHAR(50), -- ex: trim, date, decimal
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Inserir mapeamentos padrão (Exemplo)
INSERT INTO mapeamento_campos_pdf (pdf_field_pattern, db_field, transform) VALUES
('Ordem de serviço - (\\d+)', 'numero_os', 'trim'),
('Data de Abertura:\\s*(\\d{2}/\\d{2}/\\d{4})', 'data_abertura', 'date_br'),
('Responsável:\\s*(.*)', 'responsavel_aplicacao', 'trim'),
('Empresa:\\s*(.*)', 'empresa', 'trim'),
('Frente:\\s*(.*)', 'frente', 'trim'),
('Produto:\\s*(.*)', 'produto', 'trim'),
('Quantidade:\\s*([\\d\\.,]+)', 'quantidade', 'decimal_br');
