CREATE TABLE IF NOT EXISTS equipamento_operador (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plantio_diario_id BIGINT NOT NULL REFERENCES plantio_diario(id) ON DELETE CASCADE,
  trator TEXT,
  plantadora_colhedora TEXT,
  operador TEXT,
  matricula TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(plantio_diario_id)
);

-- Index for faster lookups (though unique constraint already creates one usually, explicit index on FK is good practice if not covered)
-- Postgres unique constraint creates an index on the column(s).
