-- Tabela para Controle de Liberação de Colheita
CREATE TABLE IF NOT EXISTS public.liberacao_colheita (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_liberacao TEXT NOT NULL UNIQUE,
    data DATE NOT NULL,
    frente TEXT,
    fazenda TEXT,
    fazenda_codigo TEXT,
    talhoes JSONB DEFAULT '[]'::jsonb,
    area_total NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'Pendente', -- Ex: Pendente, Liberado, Cancelado
    observacoes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices para melhor performance em filtros comuns
CREATE INDEX IF NOT EXISTS idx_liberacao_data ON public.liberacao_colheita (data);
CREATE INDEX IF NOT EXISTS idx_liberacao_fazenda ON public.liberacao_colheita (fazenda);
CREATE INDEX IF NOT EXISTS idx_liberacao_status ON public.liberacao_colheita (status);

-- Comentários da tabela e colunas (opcional, para documentação)
COMMENT ON TABLE public.liberacao_colheita IS 'Registro de liberações de áreas para colheita';
COMMENT ON COLUMN public.liberacao_colheita.talhoes IS 'Lista de talhões liberados em formato JSONB';
