-- Tabela para registrar o transporte diário de composto vinculado a uma OS (transporte_composto)
CREATE TABLE IF NOT EXISTS os_transporte_diario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    os_id UUID REFERENCES transporte_composto(id) ON DELETE CASCADE,
    data_transporte DATE NOT NULL,
    quantidade NUMERIC(10,3) NOT NULL,
    frota VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Políticas de segurança (RLS)
ALTER TABLE os_transporte_diario ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access for all users" ON os_transporte_diario
    FOR ALL
    USING (true)
    WITH CHECK (true);
