-- Tabela para armazenar as metas de plantio por frente
-- Execute este script no SQL Editor do Supabase

CREATE TABLE IF NOT EXISTS metas_plantio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    frente VARCHAR(255) NOT NULL UNIQUE,
    meta_diaria NUMERIC(10, 2) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Habilitar Row Level Security (RLS) - Opcional, mas recomendado
ALTER TABLE metas_plantio ENABLE ROW LEVEL SECURITY;

-- Política para permitir leitura pública (ajuste conforme necessidade)
CREATE POLICY "Leitura pública de metas" ON metas_plantio
    FOR SELECT USING (true);

-- Política para permitir inserção/atualização (ajuste conforme necessidade de autenticação)
CREATE POLICY "Atualização de metas" ON metas_plantio
    FOR ALL USING (true);
